version: "2"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "9001:5432"
  web:
    build:
      context: .
      target: build
      args:
        BUNDLE_INSTALL_ARGS: ""
        YARN_INSTALL_ARGS: ""
        PRECOMPILE_ASSETS: "false"
    environment:
      PORT: 9000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: dev_password
      DB_NAME: sahc_monitoring_reports_development
      VITE_RUBY_HOST: vite
    volumes:
      - .:/app
      - web_dev_cache:/dev-cache
    ports:
      - "9000:9000"
    depends_on:
      - db
      - vite
  vite:
    build:
      context: .
      target: build
      args:
        BUNDLE_INSTALL_ARGS: ""
        YARN_INSTALL_ARGS: ""
        PRECOMPILE_ASSETS: "false"
    command: ./bin/vite dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: dev_password
      DB_NAME: sahc_monitoring_reports_development
      VITE_RUBY_HOST: 0.0.0.0
    volumes:
      - .:/app
      - vite_dev_cache:/dev-cache
    ports:
      - "9002:9002"
    depends_on:
      - db
  worker:
    build:
      context: .
      target: build
      args:
        BUNDLE_INSTALL_ARGS: ""
        YARN_INSTALL_ARGS: ""
        PRECOMPILE_ASSETS: "false"
    command: bundle exec rake qc:work
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: dev_password
      DB_NAME: sahc_monitoring_reports_development
    volumes:
      - .:/app
      - worker_dev_cache:/dev-cache
    depends_on:
      - db
volumes:
  postgres_data:
  web_dev_cache:
  vite_dev_cache:
  worker_dev_cache:
